import './globals.scss'
import { Montserrat } from 'next/font/google'

import { ClientOnly, Header } from './components'
import { FeaturedPosts } from './sections'

const inter = Montserrat({ subsets: ['latin'], style: 'normal' })

export const metadata = {
  title: 'JC Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <Header />
          <FeaturedPosts />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
